// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPkJFVpLs89oxyqjSUHXn-FWkErp0LPiA',
    appId: '1:715109880290:ios:6d2f3fd3e88efde2c5e9bb',
    messagingSenderId: '715109880290',
    projectId: 'batch-file-rename-assist-d9c8a',
    storageBucket: 'batch-file-rename-assist-d9c8a.firebasestorage.app',
    iosBundleId: 'eth.hyh.batchfilerenameassistant',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANUv6oXbCD8t_s2ZkcazqRSGr0qzdJM-4',
    appId: '1:715109880290:android:c7437d899989206bc5e9bb',
    messagingSenderId: '715109880290',
    projectId: 'batch-file-rename-assist-d9c8a',
    storageBucket: 'batch-file-rename-assist-d9c8a.firebasestorage.app',
  );

}